LIBS = ../lib/parseutils.cpp ../lib/regexutils.cpp ../lib/listutils.cpp ../lib/printutils.cpp ../lib/vectorutils.cpp ../lib/nutils.cpp


first:
	g++ -O3 puzzle1.cpp $(LIBS)  -o ./first

second:
	g++ -O3 puzzle2.cpp $(LIBS) -o ./second

cleanf:
	rm -f ./first

cleans:
	rm -f ./second
